version: "3.8"

services:
  backend:
    image: ${BACKEND_IMAGE}
    container_name: url-shortener-backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: url-shortener-frontend
    ports:
      - "3000:80"
    restart: always