version: "3.8"

services:
  backend:
    image: ${DOCKER_USERNAME}/url-shortener-backend:latest
    container_name: url-shortener-server
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production

  frontend:
    image: ${DOCKER_USERNAME}/url-shortener-frontend:latest
    container_name: url-shortener-client
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  default:
    driver: bridge